controller_list:
  - name: fake_right_arm_controller
    joints:
      - RShSag
      - RShLat
      - RShYaw
      - RElbj
      - RForearmPlate
      - RWrj1
      - RWrj2
  - name: fake_right_gripper_controller
    joints:
      []